@echo off
REM ****************************************************************************
REM Vivado (TM) v2020.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Wed May 03 13:29:34 +0200 2023
REM SW Build 3064766 on Wed Nov 18 09:12:45 MST 2020
REM
REM Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim tb_buzzer_behav -key {Behavioral:sim_1:Functional:tb_buzzer} -tclbatch tb_buzzer.tcl -view P:/DE1/Cviceni/BPC-DE1-project/morse_transmitter/Transmitter_testbench.wcfg -log simulate.log"
call xsim  tb_buzzer_behav -key {Behavioral:sim_1:Functional:tb_buzzer} -tclbatch tb_buzzer.tcl -view P:/DE1/Cviceni/BPC-DE1-project/morse_transmitter/Transmitter_testbench.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
