@echo off
REM ****************************************************************************
REM Vivado (TM) v2020.2 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Sun Apr 30 11:30:31 +0200 2023
REM SW Build 3064766 on Wed Nov 18 09:12:45 MST 2020
REM
REM Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
REM elaborate design
echo "xelab -wto 38e044a08c7447369909f8e0d47354e6 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot tb_morse_bin_behav xil_defaultlib.tb_morse_bin -log elaborate.log"
call xelab  -wto 38e044a08c7447369909f8e0d47354e6 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot tb_morse_bin_behav xil_defaultlib.tb_morse_bin -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
